# Numerical Linear Algebra - Assignment 1

## Exercise 1

### a)

Wish to show that $||x||_2 \leq ||x||_1 \leq \sqrt{n} ||x||_2.$

$$ ||x||_2^2 = \sum_{i=1}^n x_i^2 \leq \bigg( \sum_{i=1}^n |x_i| \bigg)^2 = ||x||_1^2, $$

$$ ||x||_1^2 = \bigg( \sum_{i=1}^n |x_i| \bigg)^2 = \bigg( \sum_{i=1}^n 1 \cdot |x_i| \bigg)^2 \leq \bigg( \sum_{i=1}^n 1^2 \bigg) \bigg( \sum_{i=1}^n x_i^2\bigg) = n ||x||_2^2.$$

Combined this becomes

$$||x||_2 \leq ||x||_1 \leq \sqrt{n} ||x||_2,$$

which is what I wished to show.

### b)

Wish to show that $||x||_\infty \leq ||x||_2 \leq \sqrt{n} ||x||_\infty.$

$$ ||x||_\infty = \max_{1 \leq i \leq n} |x_i| = \max_{1 \leq i \leq n} \sqrt{x_i^2} \leq \bigg( \sum_{i=1}^n x_i^2 \bigg)^{1/2} = ||x||_2,$$

$$ ||x||_2^2 = \sum_{i=1}^2 x_i^2 \leq \sum_{i=1}^n \max_{1 \leq i \leq n} x_i^2 = n \cdot \bigg(\max_{1 \leq i \leq n} |x_i| \bigg)^2 = n ||x||_\infty^2.$$

Thus,

$$||x||_\infty \leq ||x||_2 \leq \sqrt{n} ||x||_\infty.$$

### c)

Wish to show that $ ||x||_\infty \leq ||x||_1 \leq n ||x||_\infty $.

$$ ||x||_\infty = \max_{1 \leq i \leq n} |x_i| \leq \sum_{i=1}^n |x_i| = ||x||_1, $$

$$ ||x||_2^2 = \sum_{i=1}^n |x_i| \leq \sum_{i=1}^n \max_{1 \leq i \leq n} |x_i| = n \cdot \max_{1 \leq i \leq n} |x_i| = n||x||_\infty. $$

Thus,

$$ ||x||_\infty \leq ||x||_1 \leq n ||x||_\infty .$$

## Exercise 2

For a matrix $A \in \mathbb{R}^{m\times n} $, the p-norm is 

$$ ||A||_p = \sup_{x \neq 0} \frac{||Ax||_p}{||x||_p} = \max_{||x||_p = 1} ||Ax||_p.$$

Thus,

$$ 
\begin{align} 
||A||_1 &= \max_{||x||_1 = 1} ||Ax||_1 = \max_{||x||_1 = 1} \sum_{i=1}^m \bigg| \sum_{j=1}^n a_{ij} x_j \bigg|  \leq \max_{||x||_1 = 1} \sum_{i=1}^m \sum_{j=1}^n | a_{ij} x_j | \\ &= \max_{||x||_1 = 1} \sum_{j=1}^n |x_j| \sum_{i=1}^m |a_{ij} | = \max_{||x||_1 = 1} ||x||_1 \sum_{i=1}^m |a_{ij} | = \max_{1 \leq j \leq n} \sum_{i=1}^m |a_{ij} |.
\end{align}
$$

Since

$$ ||Ae_k||_1 = \sum_{i=1}^m |a_{ik}| = \max_{1 \leq j \leq n} \sum_{i=1}^m |a_{ij}|, $$

where $e_k$ is the vector $e_k = (0,0,\dots,1,0, \dots, 0)$ with 1 at the k'th position, then

$$ \max_{||e_k|| = 1} ||Ae_k|| \geq ||A_1||. $$

Combined this becomes

$$ ||A||_1 = \max_{1 \leq j \leq n} \sum_{i=1}^m |a_{ij}|, $$

which is the first thing I wished to show.

Also, I have that 

$$ 
\begin{align}
    ||A||_\infty &= \max_{||x||_\infty = 1} ||Ax||_\infty = \max_{||x||_\infty = 1} \max_{1 \leq i \leq m} \bigg| \sum_{j=1}^n a_{ij} x_j \bigg| = \max_{1 \leq i \leq m} \max_{||x||_\infty = 1} \bigg| \sum_{j=1}^n a_{ij} x_j \bigg|  \\ &=  \max_{1 \leq i \leq m} \max_{||x||_\infty = 1} ||x||_\infty \sum_{j=1}^n |a_{ij}| = \max_{1 \leq i \leq m} \sum_{j=1}^n |a_{ij}|.
\end{align}
$$

So,

$$ ||A||_\infty  \leq \max_{1 \leq i \leq m} \sum_{j=1}^n |a_{ij}|. $$

## Exercise 3

I have that $ \rho (A) = \max_{\lambda \in \sigma(A)} |\lambda|$, where $\sigma (A) = \{ \lambda \in \mathbb{C} | \lambda \space \mathrm{eigenvalues \space of} \space A \}$. From this I know that

$$ Av = \lambda v, \quad v \in \mathbb{C}. $$

Thus, 

$$ |\lambda| \cdot ||v|| = || \lambda v|| = ||Av|| \leq ||A|| \cdot ||v||, $$

which for $||v|| \neq 0$ becomes $|\lambda| \leq ||A||$. As this holds for all $\lambda$ eigenvalues of $A$, then

$$ \rho(A) = \max_{\lambda \in \sigma(A)} |\lambda| \leq ||A|| $$

## Exercise 4

## Exercise 5

### a)

### b)

### c)

## Exercise 6

In [3]:
import numpy as np   
import numpy.linalg as la   
import matplotlib.pyplot as plt 
from scipy import sparse
from scipy.sparse.linalg import spsolve
from scipy.sparse.linalg import inv
from matplotlib import cm

def A_laplace(M):
    M2 = M**2
    A = -4*np.eye(M2)           
    for i in range(M2-1):
        A[i,i+1] = 1
        A[i+1,i] = 1
    for i in range(M-1,M2-1,M):
        A[i,i+1] = 0
        A[i+1,i] = 0
    for i in range(M2-M):     
        A[i,i+M] = 1
        A[i+M,i] = 1
    return A

print(A_laplace(4))

[[-4.  1. -0. -0.  1. -0. -0. -0. -0. -0. -0. -0. -0. -0. -0. -0.]
 [ 1. -4.  1. -0. -0.  1. -0. -0. -0. -0. -0. -0. -0. -0. -0. -0.]
 [-0.  1. -4.  1. -0. -0.  1. -0. -0. -0. -0. -0. -0. -0. -0. -0.]
 [-0. -0.  1. -4.  0. -0. -0.  1. -0. -0. -0. -0. -0. -0. -0. -0.]
 [ 1. -0. -0.  0. -4.  1. -0. -0.  1. -0. -0. -0. -0. -0. -0. -0.]
 [-0.  1. -0. -0.  1. -4.  1. -0. -0.  1. -0. -0. -0. -0. -0. -0.]
 [-0. -0.  1. -0. -0.  1. -4.  1. -0. -0.  1. -0. -0. -0. -0. -0.]
 [-0. -0. -0.  1. -0. -0.  1. -4.  0. -0. -0.  1. -0. -0. -0. -0.]
 [-0. -0. -0. -0.  1. -0. -0.  0. -4.  1. -0. -0.  1. -0. -0. -0.]
 [-0. -0. -0. -0. -0.  1. -0. -0.  1. -4.  1. -0. -0.  1. -0. -0.]
 [-0. -0. -0. -0. -0. -0.  1. -0. -0.  1. -4.  1. -0. -0.  1. -0.]
 [-0. -0. -0. -0. -0. -0. -0.  1. -0. -0.  1. -4.  0. -0. -0.  1.]
 [-0. -0. -0. -0. -0. -0. -0. -0.  1. -0. -0.  0. -4.  1. -0. -0.]
 [-0. -0. -0. -0. -0. -0. -0. -0. -0.  1. -0. -0.  1. -4.  1. -0.]
 [-0. -0. -0. -0. -0. -0. -0. -0. -0. -0.  1. -0. -0.  1. -4. 

In [ ]:
def initialize(M, method, omega):
    TOL = 10
    M2 = M**2
    A = A_laplace(M)
    # Source function
    def f_func(x, y): 
        return np.exp(-50*((x-1/2)**2 + (y-1/2)**2))
    
    f = np.zeros((M, M))
    for i in range(M):
        for j in range(M):
            f[i][j] = (1/M)**2 * f_func((i-1)/(M-1), (j-1)/(M-1))
    f = np.reshape(f,(M2,1))
    f = np.asarray(f).reshape(-1)
    
    As = sparse.csr_matrix(A)
    Ds = sparse.csr_matrix(np.diag(np.diag(A)))
    Es = sparse.tril(A, k=-1, format='csr')
    
    def initialize_method(method):
        print(method)
        if method == jacobi:
            print('sup')
            Ms = Ds
        if method == forward_gauss_seidel:
            print('hello')
            Ms = Ds - Es
            Ns = Ms - As
        Ns = Ms - As
        return Ms, Ns
    
    Ms, Ns = initialize_method(method)
    
    u_exact = spsolve(As,f)
    
    return A, f, As, Ds, Ms, Ns, u_exact, TOL

def jacobi(M, omega=0):
    ## Initializing variables
    A, f, As, Ds, Ms, Ns, u_exact, TOL = initialize(M, jacobi, omega)
    residuals = []
    x = []
    i = 0

    u = np.zeros(M**2)
    
    while TOL > 10**(-8):
        u = inv(Ms).dot((Ns.dot(u) + f))
        TOL = la.norm(u_exact - u)
        residuals.append(TOL)
        i += 1
        x.append(i)
    return u, u_exact, residuals, x

def forward_gauss_seidel(M, omega=0):
    ## Initializing variables
    A, f, As, Ds, Ms, Ns, u_exact, TOL = initialize(M, forward_gauss_seidel, omega)
    residuals = []
    x = []
    i = 0
    
    u = np.zeros(M**2)
    
    while TOL > 10**(-8):
        u = inv(Ms).dot((Ns.dot(u) + f))
        TOL = la.norm(u_exact - u)
        residuals.append(TOL)
        i += 1
        x.append(i)
    
    return u, u_exact, residuals, x




M = 5

J_u, u_exact, J_residuals, J_x = jacobi(M)
GS_u, u_exact, GS_residuals, GS_x = forward_gauss_seidel(M)
print('GS_u', GS_u)
print('u_exact', u_exact)    
      
# Error plot
plt.semilogy(J_x, J_residuals, label='Jacobi method')
plt.semilogy(GS_x, GS_residuals, label='Forward Gauss-Seidel method')
plt.legend()
plt.show()



<function jacobi at 0xa1961da60>
sup
<function forward_gauss_seidel at 0xa19baa158>
hello
