# Numerical Linear Algebra - Assignment 1

## Exercise 1

### a)

Wish to show that $||x||_2 \leq ||x||_1 \leq \sqrt{n} ||x||_2.$

$$ ||x||_2^2 = \sum_{i=1}^n x_i^2 \leq \bigg( \sum_{i=1}^n |x_i| \bigg)^2 = ||x||_1^2, $$

$$ ||x||_1^2 = \bigg( \sum_{i=1}^n |x_i| \bigg)^2 = \bigg( \sum_{i=1}^n 1 \cdot |x_i| \bigg)^2 \leq \bigg( \sum_{i=1}^n 1^2 \bigg) \bigg( \sum_{i=1}^n x_i^2\bigg) = n ||x||_2^2.$$

Combined this becomes

$$||x||_2 \leq ||x||_1 \leq \sqrt{n} ||x||_2,$$

which is what I wished to show.

### b)

Wish to show that $||x||_\infty \leq ||x||_2 \leq \sqrt{n} ||x||_\infty.$

$$ ||x||_\infty = \max_{1 \leq i \leq n} |x_i| = \max_{1 \leq i \leq n} \sqrt{x_i^2} \leq \bigg( \sum_{i=1}^n x_i^2 \bigg)^{1/2} = ||x||_2,$$

$$ ||x||_2^2 = \sum_{i=1}^2 x_i^2 \leq \sum_{i=1}^n \max_{1 \leq i \leq n} x_i^2 = n \cdot \bigg(\max_{1 \leq i \leq n} |x_i| \bigg)^2 = n ||x||_\infty^2.$$

Thus,

$$||x||_\infty \leq ||x||_2 \leq \sqrt{n} ||x||_\infty.$$

### c)

Wish to show that $ ||x||_\infty \leq ||x||_1 \leq n ||x||_\infty $.

$$ ||x||_\infty = \max_{1 \leq i \leq n} |x_i| \leq \sum_{i=1}^n |x_i| = ||x||_1, $$

$$ ||x||_2^2 = \sum_{i=1}^n |x_i| \leq \sum_{i=1}^n \max_{1 \leq i \leq n} |x_i| = n \cdot \max_{1 \leq i \leq n} |x_i| = n||x||_\infty. $$

Thus,

$$ ||x||_\infty \leq ||x||_1 \leq n ||x||_\infty .$$

## Exercise 2

For a matrix $A \in \mathbb{R}^{m\times n} $, the p-norm is 

$$ ||A||_p = \sup_{x \neq 0} \frac{||Ax||_p}{||x||_p} = \max_{||x||_p = 1} ||Ax||_p.$$

Thus,

$$ 
\begin{align} 
||A||_1 &= \max_{||x||_1 = 1} ||Ax||_1 = \max_{||x||_1 = 1} \sum_{i=1}^m \bigg| \sum_{j=1}^n a_{ij} x_j \bigg|  \leq \max_{||x||_1 = 1} \sum_{i=1}^m \sum_{j=1}^n | a_{ij} x_j | \\ &= \max_{||x||_1 = 1} \sum_{j=1}^n |x_j| \sum_{i=1}^m |a_{ij} | = \max_{||x||_1 = 1} ||x||_1 \sum_{i=1}^m |a_{ij} | = \max_{1 \leq j \leq n} \sum_{i=1}^m |a_{ij} |.
\end{align}
$$

Since

$$ ||Ae_k||_1 = \sum_{i=1}^m |a_{ik}| = \max_{1 \leq j \leq n} \sum_{i=1}^m |a_{ij}|, $$

where $e_k$ is the vector $e_k = (0,0,\dots,1,0, \dots, 0)$ with 1 at the k'th position, then

$$ \max_{||e_k|| = 1} ||Ae_k|| \geq ||A_1||. $$

Combined this becomes

$$ ||A||_1 = \max_{1 \leq j \leq n} \sum_{i=1}^m |a_{ij}|, $$

which is the first thing I wished to show.

Also, I have that 

$$ 
\begin{align}
    ||A||_\infty &= \max_{||x||_\infty = 1} ||Ax||_\infty = \max_{||x||_\infty = 1} \max_{1 \leq i \leq m} \bigg| \sum_{j=1}^n a_{ij} x_j \bigg| = \max_{1 \leq i \leq m} \max_{||x||_\infty = 1} \bigg| \sum_{j=1}^n a_{ij} x_j \bigg|  \\ &=  \max_{1 \leq i \leq m} \max_{||x||_\infty = 1} ||x||_\infty \sum_{j=1}^n |a_{ij}| = \max_{1 \leq i \leq m} \sum_{j=1}^n |a_{ij}|.
\end{align}
$$

So,

$$ ||A||_\infty  \leq \max_{1 \leq i \leq m} \sum_{j=1}^n |a_{ij}|. $$

## Exercise 3

I have that $ \rho (A) = \max_{\lambda \in \sigma(A)} |\lambda|$, where $\sigma (A) = \{ \lambda \in \mathbb{C} | \lambda \space \mathrm{eigenvalues \space of} \space A \}$. From this I know that

$$ Av = \lambda v, \quad v \in \mathbb{C}. $$

Thus, 

$$ |\lambda| \cdot ||v|| = || \lambda v|| = ||Av|| \leq ||A|| \cdot ||v||, $$

which for $||v|| \neq 0$ becomes $|\lambda| \leq ||A||$. As this holds for all $\lambda$ eigenvalues of $A$, then

$$ \rho(A) = \max_{\lambda \in \sigma(A)} |\lambda| \leq ||A|| $$

## Exercise 4

## Exercise 5

### a)

### b)

### c)

## Exercise 6

In [29]:
import numpy as np   
import numpy.linalg as la   
import matplotlib.pyplot as plt 
from scipy import sparse
from scipy.sparse.linalg import spsolve
from scipy.sparse.linalg import inv
from matplotlib import cm

def A_laplace(M):
    M2 = M**2
    A = -4*np.eye(M2)           
    for i in range(M2-1):
        A[i,i+1] = 1
        A[i+1,i] = 1
    for i in range(M-1,M2-1,M):
        A[i,i+1] = 0
        A[i+1,i] = 0
    for i in range(M2-M):     
        A[i,i+M] = 1
        A[i+M,i] = 1
    return A

print(A_laplace(3))

[[-4.  1. -0.  1. -0. -0. -0. -0. -0.]
 [ 1. -4.  1. -0.  1. -0. -0. -0. -0.]
 [-0.  1. -4.  0. -0.  1. -0. -0. -0.]
 [ 1. -0.  0. -4.  1. -0.  1. -0. -0.]
 [-0.  1. -0.  1. -4.  1. -0.  1. -0.]
 [-0. -0.  1. -0.  1. -4.  0. -0.  1.]
 [-0. -0. -0.  1. -0.  0. -4.  1. -0.]
 [-0. -0. -0. -0.  1. -0.  1. -4.  1.]
 [-0. -0. -0. -0. -0.  1. -0.  1. -4.]]


In [35]:
def initialize(M, method, omega):
    TOL = 10
    M2 = M**2
    A = A_laplace(M)
    # Source function
    def f_func(x, y): 
        return np.exp(-50*((x-1/2)**2 + (y-1/2)**2))
    
    f = np.zeros((M, M))
    for i in range(M):
        for j in range(M):
            f[i][j] = (1/M)**2 * f_func((i-1)/(M-1), (j-1)/(M-1))
    f = np.reshape(f,(M2,1))
    f = np.asarray(f).reshape(-1)
    
    As = sparse.csr_matrix(A)
    Ds = sparse.csr_matrix(np.diag(np.diag(A)))
    Es = sparse.tril(A, k=-1, format='csr')
    print(Es.toarray())
    
    def initialize_method(method): # Necessary with function here?
        print(method)
        if method == jacobi:
            print('sup')
            Ms = Ds
        if method == forward_gauss_seidel:
            print('hello')
            Ms = Ds - Es
        Ns = Ms - As
        print(Ns.toarray())
        return Ms, Ns
    
    Ms, Ns = initialize_method(method)
    
    u_exact = spsolve(As,f)
    
    return A, f, As, Ds, Ms, Ns, u_exact, TOL

def iterate(method, M, omega=0):
    A, f, As, Ds, Ms, Ns, u_exact, TOL = initialize(M, method, omega)
    residuals = []
    x = []
    i = 0

    u = np.zeros(M**2)
    
    while TOL > 10**(-8):
        print(TOL)
        u = inv(Ms).dot((Ns.dot(u) + f))
        TOL = la.norm(u_exact - u)
        residuals.append(TOL)
        i += 1
        x.append(i)
    return u, u_exact, residuals, x

M = 3

J_u, u_exact, J_residuals, J_x = iterate(jacobi, M)
GS_u, u_exact, GS_residuals, GS_x = iterate(forward_gauss_seidel, M)
print('GS_u', GS_u)
print('u_exact', u_exact)    
      
# Error plot
plt.semilogy(J_x, J_residuals, label='Jacobi method')
plt.semilogy(GS_x, GS_residuals, label='Forward Gauss-Seidel method')
plt.legend()
plt.show()



[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 1. 0.]]
<function jacobi at 0xa19baa840>
sup
[[ 0. -1.  0. -1.  0.  0.  0.  0.  0.]
 [-1.  0. -1.  0. -1.  0.  0.  0.  0.]
 [ 0. -1.  0.  0.  0. -1.  0.  0.  0.]
 [-1.  0.  0.  0. -1.  0. -1.  0.  0.]
 [ 0. -1.  0. -1.  0. -1.  0. -1.  0.]
 [ 0.  0. -1.  0. -1.  0.  0.  0. -1.]
 [ 0.  0.  0. -1.  0.  0.  0. -1.  0.]
 [ 0.  0.  0.  0. -1.  0. -1.  0. -1.]
 [ 0.  0.  0.  0.  0. -1.  0. -1.  0.]]
10
0.018979456008658375
0.01239098744606723
0.008570100453398134
0.00602562054856569
0.004254662208769018
0.003007422090761201
0.0021263778740098363
0.001503542504362353
0.0010631591414612981
0.0007517659849607059
0.0005315786396060489
0.0003758828278791018
0.0002657892907053551
0.00018794140879576098
0.00013289464444337656
9.397070423713

3.9659676836072955e+31
5.079517837726595e+31
6.505726602470593e+31
8.332381138961892e+31
1.0671917171951539e+32
1.366833972493766e+32
1.750608703442037e+32
2.2421383242147846e+32
2.871677865549429e+32
3.677977256989499e+32
4.710666494044178e+32
6.033310504011589e+32
7.727321746049973e+32
9.896971377036575e+32
1.2675807434568261e+33
1.6234875094320707e+33
2.0793244981728613e+33
2.6631497585185013e+33
3.410899377432112e+33
4.3685994472345577e+33
5.595199101049391e+33
7.166198997759254e+33
9.178298599929017e+33
1.1755348297723763e+34
1.50559727487909e+34
1.9283334672119212e+34
2.4697640084850504e+34
3.163215471454446e+34
4.0513717442122737e+34
5.188901343560583e+34
6.645822415992565e+34
8.511812551556865e+34
1.0901728691770998e+35
1.3962676897442364e+35
1.7883067140492177e+35
2.2904210467688456e+35
2.9335172374336413e+35
3.757179665485666e+35
4.812107070176474e+35
6.163233200573903e+35
7.893723670463425e+35
1.0110095035805615e+36
1.2948771188366235e+36
1.6584480629988736e+36


KeyboardInterrupt: 