# Numerical Linear Algebra - Assignment 1

## Exercise 1

### a)

Wish to show that $||x||_2 \leq ||x||_1 \leq \sqrt{n} ||x||_2.$

$$ ||x||_2^2 = \sum_{i=1}^n x_i^2 \leq \bigg( \sum_{i=1}^n |x_i| \bigg)^2 = ||x||_1^2, $$

$$ ||x||_1^2 = \bigg( \sum_{i=1}^n |x_i| \bigg)^2 = \bigg( \sum_{i=1}^n 1 \cdot |x_i| \bigg)^2 \leq \bigg( \sum_{i=1}^n 1^2 \bigg) \bigg( \sum_{i=1}^n x_i^2\bigg) = n ||x||_2^2.$$

Combined this becomes

$$||x||_2 \leq ||x||_1 \leq \sqrt{n} ||x||_2,$$

which is what I wished to show.

### b)

Wish to show that $||x||_\infty \leq ||x||_2 \leq \sqrt{n} ||x||_\infty.$

$$ ||x||_\infty = \max_{1 \leq i \leq n} |x_i| = \max_{1 \leq i \leq n} \sqrt{x_i^2} \leq \bigg( \sum_{i=1}^n x_i^2 \bigg)^{1/2} = ||x||_2,$$

$$ ||x||_2^2 = \sum_{i=1}^2 x_i^2 \leq \sum_{i=1}^n \max_{1 \leq i \leq n} x_i^2 = n \cdot \bigg(\max_{1 \leq i \leq n} |x_i| \bigg)^2 = n ||x||_\infty^2.$$

Thus,

$$||x||_\infty \leq ||x||_2 \leq \sqrt{n} ||x||_\infty.$$

### c)

Wish to show that $ ||x||_\infty \leq ||x||_1 \leq n ||x||_\infty $.

$$ ||x||_\infty = \max_{1 \leq i \leq n} |x_i| \leq \sum_{i=1}^n |x_i| = ||x||_1, $$

$$ ||x||_2^2 = \sum_{i=1}^n |x_i| \leq \sum_{i=1}^n \max_{1 \leq i \leq n} |x_i| = n \cdot \max_{1 \leq i \leq n} |x_i| = n||x||_\infty. $$

Thus,

$$ ||x||_\infty \leq ||x||_1 \leq n ||x||_\infty .$$

## Exercise 2

For a matrix $A \in \mathbb{R}^{m\times n} $, the p-norm is 

$$ ||A||_p = \sup_{x \neq 0} \frac{||Ax||_p}{||x||_p} = \max_{||x||_p = 1} ||Ax||_p.$$

Thus,

$$ 
\begin{align} 
||A||_1 &= \max_{||x||_1 = 1} ||Ax||_1 = \max_{||x||_1 = 1} \sum_{i=1}^m \bigg| \sum_{j=1}^n a_{ij} x_j \bigg|  \leq \max_{||x||_1 = 1} \sum_{i=1}^m \sum_{j=1}^n | a_{ij} x_j | \\ &= \max_{||x||_1 = 1} \sum_{j=1}^n |x_j| \sum_{i=1}^m |a_{ij} | = \max_{||x||_1 = 1} ||x||_1 \sum_{i=1}^m |a_{ij} | = \max_{1 \leq j \leq n} \sum_{i=1}^m |a_{ij} |.
\end{align}
$$

Since

$$ ||Ae_k||_1 = \sum_{i=1}^m |a_{ik}| = \max_{1 \leq j \leq n} \sum_{i=1}^m |a_{ij}|, $$

where $e_k$ is the vector $e_k = (0,0,\dots,1,0, \dots, 0)$ with 1 at the k'th position, then

$$ \max_{||e_k|| = 1} ||Ae_k|| \geq ||A_1||. $$

Combined this becomes

$$ ||A||_1 = \max_{1 \leq j \leq n} \sum_{i=1}^m |a_{ij}|, $$

which is the first thing I wished to show.

Also, I have that 

$$ 
\begin{align}
    ||A||_\infty &= \max_{||x||_\infty = 1} ||Ax||_\infty = \max_{||x||_\infty = 1} \max_{1 \leq i \leq m} \bigg| \sum_{j=1}^n a_{ij} x_j \bigg| = \max_{1 \leq i \leq m} \max_{||x||_\infty = 1} \bigg| \sum_{j=1}^n a_{ij} x_j \bigg|  \\ &=  \max_{1 \leq i \leq m} \max_{||x||_\infty = 1} ||x||_\infty \sum_{j=1}^n |a_{ij}| = \max_{1 \leq i \leq m} \sum_{j=1}^n |a_{ij}|.
\end{align}
$$

So,

$$ ||A||_\infty  \leq \max_{1 \leq i \leq m} \sum_{j=1}^n |a_{ij}|. $$

## Exercise 3

I have that $ \rho (A) = \max_{\lambda \in \sigma(A)} |\lambda|$, where $\sigma (A) = \{ \lambda \in \mathbb{C} | \lambda \space \mathrm{eigenvalues \space of} \space A \}$. From this I know that

$$ Av = \lambda v, \quad v \in \mathbb{C}. $$

Thus by Cauchy-Schwartz, 

$$ |\lambda| \cdot ||v|| = || \lambda v|| = ||Av|| \leq ||A|| \cdot ||v||, $$

which for $||v|| \neq 0$ becomes $|\lambda| \leq ||A||$. As this holds for all $\lambda$ eigenvalues of $A$, then

$$ \rho(A) = \max_{\lambda \in \sigma(A)} |\lambda| \leq ||A|| $$

## Exercise 4

### a)

I now wish to show that $||E||_2 = ||u||_2||v||_2$, where $E = uv^T$ and $u,v \in \mathbb{R}$. I start by showing that

$$ ||E||_2 = ||uv^T||_2 = \max_{||x||_2 = 1} ||uv^Tx||_2,$$

and since $v^Tx \in \mathbb{R}$ this can be written as

$$ ||E||_2 = ||u||_2 \max_{||x||_2 = 1} |v^Tx| = ||u||_2 \max_{||x||_2 = 1} \langle x,v \rangle.$$

As $\langle x,v \rangle$ is maximized when $x||v$ and I have the criteria that $||x||_2 = 1$, I know that 

$$ \max_{||x||_2 = 1} \langle x,v \rangle = \frac{\langle v,v \rangle}{||v||_2}. $$

Thus,

$$ ||E||_2 = ||u||_2 \frac{\langle v,v \rangle}{||v||_2} = ||u||_2 \frac{||v||_2^2}{||v||_2} = ||u||_2||v||_2 $$

### b)

Since the Frobenius norm and the 2-norm follows the same logic for vectors, the argumentation in $\textit{a)}$ will also hold for this problem, leading to

$$ ||E||_F = \max_{||x||_F = 1} ||uv^Tx||_F  = ||u||_F \max_{||x||_F = 1} \langle x,v \rangle  = ||u||_F \frac{\langle v,v \rangle}{||v||_F} = ||u||_F||v||_F. $$

## Exercise 5

$A$ is a strictly diagonally dominant matrix, thus fulfilling the criteria $ |a_{ij}| > \sum_{j \neq i} |a_{ij}|$

### a)

In Exercise 2 i proved that $ ||A||_\infty = \max_i \sum_j |a_{ij}| $. Using this property I get that

$$ ||A||_\infty = \max_i \sum_j |a_{ij}| = \max_i \bigg( |a_{ii}| + \sum_{j \neq i} |a_{ij}| \bigg) = \max_i |a_{ii}| \bigg( 1 + \frac{\sum_{j \neq i} |a_{ij}|}{|a_{ii}|} \bigg) = \max_i |a_{ii}| \space ( 1 + \alpha_i ), $$

where $\alpha_i = \frac{\sum_{j \neq i} |a_{ij}|}{|a_{ii}|} $.

### b)

I wish to prove that $||A||_\infty^{-1} \leq \frac{1}{\min_i |a_{ii}| (1-\alpha_i)} = \frac{1}{\beta}$. I start by showing that

$$ ||A^{-1}||_\infty = \sup_{x \neq 0} \frac{||A^{-1}x||_\infty}{||x||_\infty} = \sup_{Ax \neq 0} \frac{||A^{-1}Ax||_\infty}{||Ax||_\infty} = \sup_{Ax \neq 0} \frac{||x||_\infty}{||Ax||_\infty} = \sup_{x \neq 0} \frac{||x||_\infty}{||Ax||_\infty} = \bigg( \bigg( \sup_{x \neq 0} \frac{||x||_\infty}{||Ax||_\infty} \bigg)^{-1} \bigg)^{-1} = \bigg( \inf_{x \neq 0} \frac{||Ax||}{||x||} \bigg)^{-1},$$

which leads to

$$ ||A^{-1}||_\infty^{-1} = \inf_{x \neq 0} \frac{||Ax||_\infty}{||x||_\infty}. $$

Now I know that if $||A^{-1}||_\infty$ is bounded by $1/\beta$, then $\beta ||x||_\infty \leq ||Ax||_\infty$ must be satisfied. Since I know that

$$ \beta = \min_i \bigg( |a_{ii}| - \sum_{j \neq i} |a_{ij}| \bigg)  \leq |a_{ii}| - \sum_{j \neq i} |a_{ij}|,$$

one can write that

$$ \beta |x_i| \leq |a_{ii}| - \sum_{j \neq i} |a_{ij}|\space |x_j| \leq |a_{ii}| - \bigg| \sum_{j \neq i} a_{ij} x_j \bigg| \leq \bigg| \sum_{j \neq i} a_{ij} x_j \bigg| \leq \max_i  \bigg| \sum_{j \neq i} a_{ij} x_j \bigg| = ||Ax||_\infty,$$

for some vector $x$ that satisfies $|x_i| = ||x||_\infty$. Thus, I have proved $A$ is indeed bounded as

$$ ||A||_\infty^{-1} \leq \frac{1}{\min_i |a_{ii}| (1-\alpha_i)}. $$

I also wish to prove the bound $\kappa_\infty(A) \leq \tilde{\kappa}(A) := \frac{\max_i |a_{ii}| (1+\alpha_i)}{\min_i |a_{ii}|(1-\alpha_i)}$. I have from definition that

$$ \kappa_\infty(A) = ||A||_\infty ||A^{-1}||_\infty. $$

Combined with the expressios for $||A||_\infty$ and $||A^{-1}||_\infty$ as calculated above, this becomes

$$ \kappa_\infty(A) = ||A||_\infty ||A^{-1}||_\infty \leq \max_i |a_{ii}| \space ( 1 + \alpha_i ) \cdot \frac{1}{\min_i |a_{ii}| (1-\alpha_i)} = \frac{\max_i |a_{ii}| (1+\alpha_i)}{\min_i |a_{ii}|(1-\alpha_i)} = \tilde{\kappa}(A)$$

### c)

## Exercise 6

In [81]:
import numpy as np   
import numpy.linalg as la   
import matplotlib.pyplot as plt 
from scipy import sparse
from scipy.sparse.linalg import spsolve
from scipy.sparse.linalg import inv
from scipy.sparse.linalg import spilu
from matplotlib import cm
import time

def A_laplace(M):
    M2 = M**2
    A = -4*np.eye(M2)           
    for i in range(M2-1):
        A[i,i+1] = 1
        A[i+1,i] = 1
    for i in range(M-1,M2-1,M):
        A[i,i+1] = 0
        A[i+1,i] = 0
    for i in range(M2-M):     
        A[i,i+M] = 1
        A[i+M,i] = 1
    return A

print(A_laplace(3))

[[-4.  1. -0.  1. -0. -0. -0. -0. -0.]
 [ 1. -4.  1. -0.  1. -0. -0. -0. -0.]
 [-0.  1. -4.  0. -0.  1. -0. -0. -0.]
 [ 1. -0.  0. -4.  1. -0.  1. -0. -0.]
 [-0.  1. -0.  1. -4.  1. -0.  1. -0.]
 [-0. -0.  1. -0.  1. -4.  0. -0.  1.]
 [-0. -0. -0.  1. -0.  0. -4.  1. -0.]
 [-0. -0. -0. -0.  1. -0.  1. -4.  1.]
 [-0. -0. -0. -0. -0.  1. -0.  1. -4.]]


In [121]:
def initialize(M, method, omega):
    TOL = 10
    M2 = M**2
    A = A_laplace(M)
    # Source function
    def f_func(x, y): 
        return np.exp(-50*((x-1/2)**2 + (y-1/2)**2))
    
    f = np.zeros((M, M))
    for i in range(M):
        for j in range(M):
            f[i][j] = (1/M)**2 * f_func((i-1)/(M-1), (j-1)/(M-1))
    f = np.reshape(f,(M2,1))
    f = np.asarray(f).reshape(-1)
    
    As = sparse.csc_matrix(A)
    Ds = sparse.csc_matrix(np.diag(np.diag(A)))
    Es = sparse.tril(A, k=-1, format='csc')
    print(Es.toarray())
    
    def initialize_method(method): # Necessary with function here?
        print(method)
        if method == 'jacobi':
            Ms = Ds
            #inv_Ms = inv(Ms)
        if method == 'forward_gauss_seidel':
            Ms = Ds + Es
            #inv_Ms = inv(Ms)
        if method == 'successive_over_relaxation':
            Ms = 1/omega * Ds + Es
            #inv_Ms = inv(Ms)
        if method == 'incomplete_LU':
            Ms = spilu(A)   #z[M.perm-c]=x
            x = Ms.solve(b)
            z = np.zeros(M**2)
            z[Ms.perm_c] = M**2
            z = Ms.L.dot(Ms.U.dot(z))
            z = z[Ms.perm_r]
            print('z', z)
            Ms = z
            #Ls = sparse.csc_matrix(Ms.L.A)
            #Us = sparse.csc_matrix(Ms.U.A)
            #inv_Ms = Ls*Us
            #Ms = inv(inv_Ms)
        Ns = Ms - As
        #print('inv',inv_Ms.toarray())
        print('Ns',Ns)#.toarray())
        return Ms, Ns
    
    Ms, Ns = initialize_method(method)
    
    u_exact = spsolve(As,f)
    
    return A, f, As, Ds, Ms, Ns, u_exact, TOL

def iterate(M, method, omega=0):
    start = time.time()
    A, f, As, Ds, Ms, Ns, u_exact, TOL = initialize(M, method, omega)
    residuals = []
    x = []
    i = 0

    u = np.zeros(M**2)
    
    while TOL > 10**(-10):
        #print(TOL)
        u = spsolve(Ms, Ns.dot(u) + f)
        TOL = la.norm(u_exact - u,2)
        residuals.append(TOL)
        i += 1
        x.append(i)
    end = time.time()
    used_time = end - start
    return u, u_exact, residuals, x, used_time

M = 5
omega = 1.5

J_u, u_exact, J_residuals, J_x, J_used_time = iterate(M, 'jacobi')
print('J_x:', J_x[-1])
FGS_u, u_exact, FGS_residuals, FGS_x, FGS_used_time = iterate(M, 'forward_gauss_seidel')
print('FGS_x:', FGS_x[-1])
SOR_u, u_exact, SOR_residuals, SOR_x, SOR_used_time = iterate(M, 'successive_over_relaxation', omega) 
print('SOR_x:', SOR_x[-1])
ILU_u, u_exact, ILU_residuals, ILU_x, ILU_used_time = iterate(M, 'incomplete_LU')
      
# Error plot
plt.semilogy(J_x, J_residuals, label='Jacobi method, time: '+str(round(J_used_time,5)))
plt.semilogy(FGS_x, FGS_residuals, label='Forward Gauss-Seidel method, time: '+str(round(FGS_used_time, 5)))
plt.semilogy(SOR_x, SOR_residuals, label='Successive over relaxation, time: '+str(round(SOR_used_time, 5)))
plt.semilogy(ILU_x, ILU_residuals, label='Incomplete LU factorization')
plt.xlabel('Number of steps')
plt.ylabel('Error norm')
plt.legend()
plt.show()



[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 1. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 1. 0.

/Users/ellajohnsen/anaconda3/lib/python3.7/site-packages/scipy/sparse/linalg/dsolve/linsolve.py:133: SparseEfficiencyWarning: spsolve requires A be CSC or CSR matrix format
  SparseEfficiencyWarning)


ValueError: matrix must be square (has shape (1, 25))